#!/bin/sh
set -e

# Read secrets from shared volume (generated by init-secrets container)
if [ -z "$DB_PASSWORD" ] && [ -f /app/data/.db_password ]; then
    export DB_PASSWORD=$(cat /app/data/.db_password)
fi

if [ -z "$JWT_SECRET" ] && [ -f /app/data/.jwt_secret ]; then
    export JWT_SECRET=$(cat /app/data/.jwt_secret)
fi

# Fallback: generate if still empty (non-Docker usage)
if [ -z "$DB_PASSWORD" ]; then
    export DB_PASSWORD=$(openssl rand -hex 16)
    echo "[ersub] WARNING: DB_PASSWORD not set and no secrets file found. Generated ephemeral password."
fi

if [ -z "$JWT_SECRET" ]; then
    export JWT_SECRET=$(openssl rand -hex 32)
    echo "[ersub] WARNING: JWT_SECRET not set and no secrets file found. Generated ephemeral secret."
fi

echo "[ersub] Starting — DB_HOST=$DB_HOST:$DB_PORT DB_USER=$DB_USER"

exec bin/ersub foreground
